### ISSUE TITLE
Teaching children how to write javascript code using p5js-toolbar

### ISSUE THREAD

**Issue by PoppaAL** [bmoren/p5js-toolbar#7]
Hello,
I,m 77 years old and trying to teach my seven grandchildren to write and understand code. P5.js Toolbar
seems to be the perfect fit for this project. The one short drawback to starting to teach to my grandchildren, is showing a function in a program (In P5.js Toolbar)  and to get to the reference that explains the function.
The thing I'm asking for, is when I hover over the p5js function, be able to toggle to that function in the
p5js reference back and forth. As you can see, that in itself, is a training tool to learn p5js functions and which they can tinker with.

**Comment by bmoren** [comment]
Hi @PoppaAL ! Thanks for the recommendation. I have another package - https://github.com/bmoren/p5js-snippets which provides this type of support! have a look. someday I hope to integrate the two into a single p5.js package.

**Comment by PoppaAL** [comment]
bmoren,
Thank you for the p5js-snippets. I think it might just do the thing for me. Thanks again PoppaAl.
